import Image from 'next/image';
import dynamic from 'next/dynamic';
import { getPricingTiers } from '@/utils/server/prices';
import { notFound } from 'next/navigation';
// Components
import AnimateX from '@/components/AnimateX';
import Footer from '@/components/Footer';
// import PricingBox from './PricingBox';
// Images
import imgGraph from '@/../public/Purchase-page-graph.jpg';
import imgBeginLogoCount from '@/../public/Beginning-logo-count.jpg';
import imgBeginARR from '@/../public/Beginning-ARR.jpg';
// Styles
import styles from './page.module.scss';

const PricingBox = dynamic(() => import('./PricingBox'), { ssr: false }); // Prevent FOUC


const PurchasePage = async () => {
  const tiers = await getPricingTiers();
  if (!tiers)
    notFound();

  return (
    <AnimateX>
      <main>
        <section className={styles.s1}>
          <div className={styles.vflex}>
            <div className={styles.title} data-animated="text1">Great Analysis.<br />Instantly</div>
            <div className={styles.txt} data-animated="text1" data-anim-delay=".1">We offer beautiful charts and analysis, accurately, and instantly</div>
            <Image alt="Average ARR per Customer" src={imgGraph} className={styles.img} priority data-animated="text1" data-anim-delay=".2" />
          </div>
        </section>

        <section className={styles.s2}>
          <div className={styles.vflex}>
            <div className={styles.title} data-animated="text1">What’s Included</div>
            <div className={styles.grid}>
              <div className={styles.cell} data-animated="text1">
                <div className={styles.title}>ARR Waterfalls</div>
                <div className={styles.txt}>The add-in automatically generates annualized TTM ARR waterfalls, ready to
                  drop straight into Investment Committee materials
                </div>
              </div>
              <div className={styles.cell} data-animated="text1" data-anim-delay="0.2">
                <div className={styles.title}>Cohort Analysis</div>
                <div className={styles.txt}>Run sophisticated cohort analysis on a monthly, quarterly, or annual basis
                  to better understand revenue evolution over time
                </div>
              </div>
              <div className={styles.cell} data-animated="text1" data-anim-delay="0.4">
                <div className={styles.title}>Retention Analysis</div>
                <div className={styles.txt}>Automatically generate gross and net dollar retention including and
                  excluding downsell, to better understand sales needs to “fill the bucket”
                </div>
              </div>
              <div className={styles.cell} data-animated="text1">
                <div className={styles.title}>Automated Segmentation</div>
                <div className={styles.txt}>The add-in automatically customer size, location, and end-market vertical so
                  you can better understand your revenue trends by customer segment
                </div>
              </div>
              <div className={styles.cell} data-animated="text1" data-anim-delay="0.2">
                <div className={styles.title}>ACV Analysis</div>
                <div className={styles.txt}>Learn how your average customer spend is evolving over time, cut by
                  customers segments that are automatically generated by the tool
                </div>
              </div>
              <div className={styles.cell} data-animated="text1" data-anim-delay="0.4">
                <div className={styles.title}>Monthly, Quarterly, and Annually</div>
                <div className={styles.txt}>Select the time period that is right for your business. The tool can
                  generate analysis and reporting on a multi-period basis to ensure ease of use and digestion
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className={styles.s3}>
          <div className={styles.grid}>
            <Image alt="Beginning Logo Count" src={imgBeginLogoCount} className={styles.img} data-animated="text1" />
            <Image alt="Beginning ARR" src={imgBeginARR} className={styles.img} data-animated="text1" />
          </div>
        </section>

        <section className={styles.s4}>
          <div className={styles.vflex}>
            <div className={styles.title} data-animated="text1">Pricing Options</div>
            <div className={styles.grid}>
              <PricingBox tier={tiers.One} />
              <PricingBox tier={tiers.Two} animDelay={.2} />
              <PricingBox tier={tiers.Three} animDelay={.4} />
            </div>
          </div>
        </section>

        <section className={styles.s5}>
          <div className={styles.inner}>
            <div className={styles.titleq} data-animated="text1">What people are saying</div>
            <div className={styles.saying}>
              <div className={styles.single} data-animated="text1">
                <div className={styles.say}>“This has probably saved me 100 hours in the past three months. The best
                  tool I use.”
                </div>
                <div className={styles.who}>— Analyst, Leading Growth Equity Firm</div>
              </div>
              <div className={styles.single} data-animated="text1" data-anim-delay="0.2">
                <div className={styles.say}>“This is now our firm standard. The tool generates analysis we hadn’t
                  previously considered when assessing investments.”
                </div>
                <div className={styles.who}>— Partner, Leading Software Private Equity Firm</div>
              </div>
            </div>
          </div>
        </section>

        <section className={styles.s6}></section>

        <Footer />
      </main>
    </AnimateX>
  );
};


export default PurchasePage;
