import Image from 'next/image';
import cn from 'classnames';
import AnimateX from '@/components/AnimateX';
import PricingBox from '@/app/(main)/purchase/pricing-box';
// Images
import imgGraph from '@/../public/Purchase-page-graph.jpg';
import imgBeginLogoCount from '@/../public/Beginning-logo-count.jpg';
import imgBeginARR from '@/../public/Beginning-ARR.jpg';
// Styles
import styles from './page.module.scss';


const PurchasePage = () => {
  return (
    <AnimateX>
      <main>
        <section className={styles.s1}>
          <div className={styles.vflex}>
            <div className={styles.title}>Great Anaysis. Instantly</div>
            <div className={styles.txt}>We offer beautiful charts and analysis, accurately, and instantly</div>
            <Image alt="Average ARR per Customer" src={imgGraph} className={styles.img} priority />
          </div>
        </section>

        <section className={styles.s2}>
          <div className={styles.vflex}>
            <div className={styles.title}>What’s Included</div>
            <div className={styles.grid}>
              <div className={styles.cell}>
                <div className={styles.title}>ARR Waterfalls</div>
                <div className={styles.txt}>The add-in automatically generates annualized TTM ARR waterfalls, ready to
                  drop straight into Investment Committee materials
                </div>
              </div>
              <div className={styles.cell}>
                <div className={styles.title}>Cohort Analysis</div>
                <div className={styles.txt}>Run sophisticated cohort analysis on a monthly, quarterly, or annual basis
                  to better understand revenue evolution over time
                </div>
              </div>
              <div className={styles.cell}>
                <div className={styles.title}>Retention Analysis</div>
                <div className={styles.txt}>Automatically generate gross and net dollar retention including and
                  excluding downsell, to better understand sales needs to “fill the bucket”
                </div>
              </div>
              <div className={styles.cell}>
                <div className={styles.title}>Automated Segmentation</div>
                <div className={styles.txt}>The add-in automatically customer size, location, and end-market vertical so
                  you can better understand your revenue trends by customer segment
                </div>
              </div>
              <div className={styles.cell}>
                <div className={styles.title}>ACV Analysis</div>
                <div className={styles.txt}>Learn how your average customer spend is evolving over time, cut by
                  customers segments that are automatically generated by the tool
                </div>
              </div>
              <div className={styles.cell}>
                <div className={styles.title}>Monthly, Quarterly, and Annually</div>
                <div className={styles.txt}>Select the time period that is right for your business. The tool can
                  generate analysis and reporting on a multi-period basis to ensure ease of use and digestion
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className={styles.s3}>
          <div className={styles.grid}>
            <Image alt="Beginning Logo Count" src={imgBeginLogoCount} className={styles.img} />
            <Image alt="Beginning ARR" src={imgBeginARR} className={styles.img} />
          </div>
        </section>

        <section className={styles.sTemp}>
          <div className={cn(styles.inner, styles.dark)}>
            <PricingBox />
            <PricingBox />
          </div>
          <div className={cn(styles.inner, styles.light)}>
            <PricingBox/>
            <PricingBox />
          </div>
        </section>
      </main>
    </AnimateX>
  );
};


export default PurchasePage;
