import Image from 'next/image';
import SubmitForm from './submit-form';
import { K_Theme } from '@/utils/common';
// Components
import AnimateX from '@/components/AnimateX';
import LinkButton from '@/components/LinkButton';
import Footer from '@/components/Footer';
// Images
import imgGraph from '@/../public/Purchase-page-graph.jpg';
import imgBeginLogoCount from '@/../public/Beginning-logo-count.jpg';
import imgBeginARR from '@/../public/Beginning-ARR.jpg';
import imgCol1 from '@/../public/ACV-over-time.jpg';
import imgCol2 from '@/../public/Cohort-analysis.jpg';
import imgCol3 from '@/../public/Rolling-unit-economics.jpg';
// Styles
import styles from './page.module.scss';


const ProductPage = () => {
  return (
    <AnimateX>
      <main className={styles.main}>
        <section className={styles.s1}>
          <div className={styles.centrer}>
            <div className={styles.titleText} data-animated="text1">For SaaS Investors, Software Executives, or anyone
              who works with subscription revenue analysis. The ARR Analysis Excel Add-in reduces time in spreadsheets
              and helps you focus on what matters
            </div>
            <div className={styles.spacer} />
            <div data-animated="text1" data-anim-delay=".5">
              <LinkButton theme={K_Theme.Light} href="/purchase">
                Try it out
              </LinkButton>
            </div>
          </div>
        </section>

        <section className={styles.s2}>
          <div className={styles.vflex}>
            <div className={styles.title} data-animated="text1">Great Analysis.<br />Instantly</div>
            <div className={styles.txt} data-animated="text1" data-anim-delay=".1">We offer beautiful charts and analysis, accurately, and instantly</div>
            <Image alt="Average ARR per Customer" src={imgGraph} className={styles.img} priority data-animated="text1" data-anim-delay=".2" />
          </div>
        </section>

        <section className={styles.s3}>
          <div className={styles.vflex}>
            <div className={styles.title} data-animated="text1">What’s Included</div>
            <div className={styles.grid}>
              <div className={styles.cell} data-animated="text1">
                <div className={styles.title}>ARR Waterfalls</div>
                <div className={styles.txt}>The add-in automatically generates annualized TTM ARR waterfalls, ready to
                  drop straight into Investment Committee materials
                </div>
              </div>
              <div className={styles.cell} data-animated="text1" data-anim-delay="0.2">
                <div className={styles.title}>Cohort Analysis</div>
                <div className={styles.txt}>Run sophisticated cohort analysis on a monthly, quarterly, or annual basis
                  to better understand revenue evolution over time
                </div>
              </div>
              <div className={styles.cell} data-animated="text1" data-anim-delay="0.4">
                <div className={styles.title}>Retention Analysis</div>
                <div className={styles.txt}>Automatically generate gross and net dollar retention including and
                  excluding downsell, to better understand sales needs to “fill the bucket”
                </div>
              </div>
              <div className={styles.cell} data-animated="text1">
                <div className={styles.title}>Automated Segmentation</div>
                <div className={styles.txt}>The add-in automatically customer size, location, and end-market vertical so
                  you can better understand your revenue trends by customer segment
                </div>
              </div>
              <div className={styles.cell} data-animated="text1" data-anim-delay="0.2">
                <div className={styles.title}>ACV Analysis</div>
                <div className={styles.txt}>Learn how your average customer spend is evolving over time, cut by
                  customers segments that are automatically generated by the tool
                </div>
              </div>
              <div className={styles.cell} data-animated="text1" data-anim-delay="0.4">
                <div className={styles.title}>Monthly, Quarterly, and Annually</div>
                <div className={styles.txt}>Select the time period that is right for your business. The tool can
                  generate analysis and reporting on a multi-period basis to ensure ease of use and digestion
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className={styles.s4}>
          <div className={styles.grid}>
            <Image alt="Beginning Logo Count" src={imgBeginLogoCount} className={styles.img} data-animated="text1" />
            <Image alt="Beginning ARR" src={imgBeginARR} className={styles.img} data-animated="text1" />
          </div>
        </section>

        <section className={styles.s5}>
          <div className={styles.centrer}>
            <div className={styles.titleText} data-animated="text1">All your revenue analysis requirements, automated, and in one place.</div>
            <div className={styles.grid}>
              <div className={styles.imgDesc} data-animated="text1">
                <Image alt="ACV Over Time" src={imgCol1} className={styles.img} priority />
                <div className={styles.desc}>ACV Over Time</div>
              </div>
              <div className={styles.imgDesc} data-animated="text1" data-anim-delay="0.2">
                <Image alt="Cohort Analysis" src={imgCol2} className={styles.img} priority />
                <div className={styles.desc}>Cohort Analysis</div>
              </div>
              <div className={styles.imgDesc} data-animated="text1" data-anim-delay="0.4">
                <Image alt="Rolling Unit Economics" src={imgCol3} className={styles.img} />
                <div className={styles.desc}>Rolling Unit Economics</div>
              </div>
            </div>
            <div className={styles.vesaire} data-animated="text1">And so much more</div>
          </div>
        </section>

        <section className={styles.s6}>
          <SubmitForm />
        </section>

        <section className={styles.s7} />

        <Footer />
      </main>
    </AnimateX>
  );
};


export default ProductPage;
